[package]
name = "he-ring"
version = "0.1.1"
edition = "2021"

repository = "https://github.com/FeanorTheElf/he-ring"
homepage = "https://github.com/FeanorTheElf/he-ring"
keywords = ["cryptography", "homomorphic encryption"]
readme = "Readme.md"
description = "A library that provides fast implementations of rings commonly used in homomorphic encryption, built on feanor-math."
license = "MIT"

[lib]
crate-type = ["rlib"]
bench = true

[dependencies]
feanor-math = { version = "1.5.2", features = ["generic_tests"] }
rand = "0.8.5"
rand_distr = "0.4.3"

[features]
record_timings = []

[profile.profiling]
inherits = "bench"
debug = true
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
