[package]
name = "he-ring"
version = "0.3.1"
edition = "2021"

repository = "https://github.com/FeanorTheElf/he-ring"
homepage = "https://github.com/FeanorTheElf/he-ring"
keywords = ["cryptography", "encryption", "fhe", "homomorphic", "fhe"]
readme = "Readme.md"
description = "A library that provides fast implementations of rings commonly used in homomorphic encryption, built on feanor-math."
license = "MIT"

[lib]
crate-type = ["rlib"]
bench = true

[dependencies]
feanor-math = { version = "1.7.3", features = ["generic_tests"] }

[dev-dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
oorandom = "11.1.3"

[features]
record_timings = []
force_naive_gadget_product = []

[profile.profiling]
inherits = "bench"
debug = true
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
